image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: './Main.py'

vscode:
  extensions:
    - sourcery.sourcery@0.8.6:HKaqb4fBNrcGfvm8+UK0+A==